### ISSUE TITLE
The component doesn't function correctly in safari and any IOS platform.

### ISSUE THREAD

**Issue by danjaviacm** [ianmcnally/react-input-completion#5]
<img width="1056" alt="captura de pantalla 2016-02-23 a las 1 58 24 p m" src="https://cloud.githubusercontent.com/assets/16091250/13262969/8e4140f8-da35-11e5-95c3-70c41b7a5f4d.png">

**Comment by ianmcnally** [comment]
It's hard for me to debug with no information provided. Do you have a working example I can look at?

There are several things that could cause it not to render, so for me to help you track down whether it's a project bug or user input error, I need to know more. Like, are you passing it an array of options? Is it set to `defaultNative`? Does the same code work in other browsers?

**Comment by danjaviacm** [comment]
I send to you the screenshot.

the issue occurs in the IOS system

Thanks in advance!

**Comment by ianmcnally** [comment]
@danjaviacm the screenshot tells me nothing about how you're using it, besides you're building a website for cars. github issues are a space to collaborate on code, not for maintainers to provide blind customer support. so i can only give you as much help as you give me.

**Comment by ianmcnally** [comment]
FYI: I'm running the examples in `demo/`. It's functioning as expected. Not exactly winning any awards, unstyled:

![screen shot 2016-02-23 at 17 30 51](https://cloud.githubusercontent.com/assets/1494758/13268943/3c297448-da53-11e5-9271-5a440be6850d.png)

Have you checked whether the dropdown is actually rendering? Depending on your styling, the options could be obscured by other elements.

**Comment by ianmcnally** [comment]
And on iOS:

<img width="352" alt="screen shot 2016-02-23 at 17 33 27" src="https://cloud.githubusercontent.com/assets/1494758/13269013/9600c34a-da53-11e5-8efe-6ba0174b1e12.png">

**Comment by ianmcnally** [comment]
Now that I look at your screenshot more, I realize react-input-completion is functioning. 

<img width="132" alt="screen shot 2016-02-23 at 17 35 15" src="https://cloud.githubusercontent.com/assets/1494758/13269052/d578eade-da53-11e5-8c7c-21b5ca709208.png">

Since Safari and mobile Safari don't support `<datalist>` natively, you're seeing the unstyled non-native version. Styling is provided in this project, in react-input-completion.css (see the node_modules dir) in your project. Otherwise, you'll have to style it yourself.

**Comment by danjaviacm** [comment]
In IOS and safari when I click the li elements. It's not have any action

**Comment by ianmcnally** [comment]
With the example in this repo, I can click them fine in Safari. Without a usable test case, I'm afraid I can't help you any further.

There is a mobile safari tap issue I'm seeing that I'll look in to.

**Comment by danjaviacm** [comment]
thanks
